1214 rapatriement xp no code relance des entreprise pour devenir EA   partie 4 relance
gip-inclusion/immersion-facile pull request #1229
Opened 2024-02-06 13:20 UTC by clement-duport

2024-02-15 16:34 UTC, JeromeBu requested changes

2024-02-15 16:34 UTC, JeromeBu commented on back/src/adapters/secondary/InMemoryConventionQueries.ts
> +        return acc;
Les mutations dans les accumulateurs sont souvent source de problèmes. On préfère être immuable autant que possible. De plus il semple que tout ce reduce est en fait simplifiable en un filter.

Et on constate aussi avec @celineung que le fait de commenter le .reduce ne casse aucun test. Il faut donc en écrire un.

2024-02-15 16:34 UTC, JeromeBu commented on back/src/adapters/secondary/offer/InMemoryEstablishmentLeadRepository.ts
> +    return Promise.resolve(sirets);
Pourquoi cette histoire de longueur === 1 ? 

On veut juste le dernier qui match non ? Et on doit pouvoir le faire en un seul filtre.

Et on peut faire une fonction async pour éviter le promise.resolve.

Un truc du genre :

```suggestion
    return Object.values(this.#establishmentLeads)
      .filter(
        ({ lastEventKind, events }) => {
          const lastEvent = events.at(-1)
          if(lastEvent?.kind !== kind) return false;
          if(!beforeDate) return true;
          return lastEvent.occurredAt <= beforeDate
      })
      .map(({ siret }) => siret);
```

2024-02-15 16:34 UTC, JeromeBu commented on back/src/adapters/secondary/pg/migrations/1707916073655_delete-all-from-establishment-lead-events-table.ts
> +export const shorthands: ColumnDefinitions | undefined = undefined;
```suggestion

import { MigrationBuilder } from "node-pg-migrate";

```

2024-02-15 17:13 UTC, celineung commented on back/src/adapters/secondary/InMemoryConventionQueries.ts
> +        return acc;
@JeromeBu j'ai complété le test, mais après être repassé dessus, on a bien besoin d'un `reduce` ou équivalent. Mais un `filter` ne permettrait pas de récupérer seulement la dernière convention par siret.

2024-02-15 17:25 UTC, celineung commented on back/src/adapters/secondary/offer/InMemoryEstablishmentLeadRepository.ts
> +    return Promise.resolve(sirets);
> Pourquoi cette histoire de longueur === 1 ? 
> On veut juste le dernier qui match non ? Et on doit pouvoir le faire en un seul filtre.

On vérifie qu'il n'y a qu'une seul event du type `kind` car dans le cas du `reminder-sent` il peut y en avoir deux une fois les deux relances faite

2024-02-16 10:08 UTC, celineung commented on shared/src/routes/establishmentLeadRoutes.ts
> +      200: expressEmptyResponseBody,
HTTP 201 signifie `created`.
Pourquoi pas juste une HTTP 204 pour répondre `no content` ?

2024-02-16 10:23 UTC, JeromeBu commented on shared/src/routes/establishmentLeadRoutes.ts
> +      200: expressEmptyResponseBody,
Pourquoi pas oui. Mais en tout cas pas 200 avec une réponse vide

2024-02-16 11:01 UTC, celineung commented on back/src/adapters/secondary/offer/InMemoryEstablishmentLeadRepository.ts
> +    return Promise.resolve(sirets);
Pour reprendre ta suggestion, il faudrait rajouter un tri sur les events + vérifier que l'event n'ait eu lieu qu'une seule fois:

```js
return Object.values(this.#establishmentLeads)
      .filter(
        ({ events }) => {
          const sortedEvents = events.sort((event1, event2) => event2.occurredAt.getMilliseconds() - event1.occurredAt.getMilliseconds() );

          const lastEvent = sortedEvents.at(-1)
          if(lastEvent?.kind !== kind || events.filter((event) => event.kind === kind).length > 1) return false;
          if(!beforeDate) return true;

          return lastEvent.occurredAt <= beforeDate
        })
      .map(({ siret }) => siret);
```

2024-02-19 10:17 UTC, JeromeBu commented on back/src/domain/convention/useCases/notifications/NotifyLastSigneeThatConventionHasBeenSigned.ts
> +    }
idem

2024-02-19 14:57 UTC, JeromeBu commented on front/src/core-logic/domain/establishmentLead/establishmentLead.epics.ts
> +    map((_result) =>
```suggestion
    map(() =>
```

Etant donnée que le retour est void on doit même pouvoir simplifier plus comme ça :

```ts
map(establishmentLeadSlice.actions.unsubscribeEstablishmentLeadSucceeded)
```

2024-02-20 08:37 UTC, JeromeBu approved these changes

2024-02-22 15:41 UTC, merged