1263 etq agence prescripteur je ne reois pas de mail pour minformer que une structure daccompagnement vient de se rfrencer et ma choisit comme structure prescriptrice
gip-inclusion/immersion-facile pull request #1339
Opened 2024-03-04 14:17 UTC by clement-duport

- add email template to notify agency that accompanying agency got activated
- send email to notify agency that accompanying agency got activated

2024-03-04 14:22 UTC, enguerranws commented on back/src/domains/convention/use-cases/SendEmailsWhenAgencyIsActivated.ts
> +          ? [...agency.counsellorEmails]
Il y a un intérêt à destructurer ça ?

2024-03-04 14:23 UTC, enguerranws commented on back/src/domains/convention/use-cases/SendEmailsWhenAgencyIsActivated.ts
> +          recipients: [...agencyReferredTo.validatorEmails],
idem ici ?

2024-03-04 14:24 UTC, enguerranws commented on back/src/domains/convention/use-cases/SendEmailsWhenAgencyIsActivated.unit.test.ts
> +  it("send a notification email to validating agency when accompagnying agency was activated and one activation email to the counsellors of the acompanying agency", async () => {
accompagnying => accompanying

2024-03-04 14:29 UTC, enguerranws commented on back/src/domains/convention/use-cases/SendEmailsWhenAgencyIsActivated.ts
> +          kind: "ACCOMPANYING_AGENCY_WITH_AGENCY_REFERS_TO_NOTIFICATION",
j'ai un doute sur le nommage de ce type de mail... on utilise jamais le terme "accompanying agency" et on a pas la notion de l'agence activée.  `AGENCY_REFERS_TO_ACTIVATED` ?

2024-03-04 19:37 UTC, JeromeBu requested changes

2024-03-04 19:37 UTC, JeromeBu commented on back/src/domains/convention/use-cases/SendEmailsWhenAgencyIsActivated.ts
> +            accompanyingAgencyName: agency.name,
```suggestion
            nameOfAgencyRefering: agency.name,
```

2024-03-04 19:37 UTC, JeromeBu commented on back/src/domains/convention/use-cases/SendEmailsWhenAgencyIsActivated.unit.test.ts
> +  .build();
pas fan de ce terme : accompanying
je te propose :
```suggestion
const agencyWithRefersTo = new AgencyDtoBuilder()
  .withId("id-of-agency-refering-to-other")
  .withRefersToAgencyId(agency.id)
  .withCounsellorEmails(["councellor@email.com"])
  .withValidatorEmails(agency.validatorEmails)
  .withName("just-activated-agency-refering-to-other-one")
  .withLogoUrl("https://agency-refering-logo.com")
  .build();
```

2024-03-04 19:37 UTC, JeromeBu commented on back/src/domains/convention/use-cases/SendEmailsWhenAgencyIsActivated.unit.test.ts
> +  it("throw not found error if no agency were found with agency refers to id when accompanying agency activated", async () => {
```suggestion
  it("throw not found error if no agency were found with agency refers to id when agency refering to other activated", async () => {
```

2024-03-05 08:34 UTC, celineung approved these changes

2024-03-05 08:43 UTC, JeromeBu approved these changes

2024-03-05 08:53 UTC, merged