Release notes automatiques
gip-inclusion/immersion-facile pull request #1353
Opened 2024-03-05 17:21 UTC by celineung

2024-03-06 19:55 UTC, JeromeBu requested changes

2024-03-06 19:55 UTC, JeromeBu commented on .github/workflows/continous-delivery.yml
>        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
les valeurs sont disponibles en `secrets`, il ne faut pas la mettre dans with car dans ce cas elles apparaitrons en clair dans les logs.

2024-03-06 19:55 UTC, JeromeBu commented on .github/workflows/deploy-to-scalingo.yml
> +        required: true
à supprimer et utiliser les secrets à la place. Je suis curieux de comprendre ce qui a motivé ce changement, étant donnée que ça fonctionnait déjà avec les secrets ?

2024-03-07 08:29 UTC, JeromeBu commented on .github/workflows/continous-delivery.yml
> +    needs: [ deploy-staging, deploy-prod ]
Juste la prod ca doit suffire 
```suggestion
    needs: [ deploy-prod ]
```

2024-03-07 08:29 UTC, celineung commented on .github/workflows/deploy-to-scalingo.yml
> +        required: true
@JeromeBu le `with` était directement dans la racine du job `deploy-staging` avant.
Mais j'utilise maintenant des `steps` et je n'ai pas l'impression qu'il soit possible d'utiliser `with` dans une step

2024-03-07 08:31 UTC, celineung commented on .github/workflows/continous-delivery.yml
> +    needs: [ deploy-staging, deploy-prod ]
@JeromeBu on a besoin de ce needs pour accéder aux variables créées sur `deploy-staging`

2024-03-07 14:09 UTC, JeromeBu approved these changes

2024-03-07 14:12 UTC, merged