#1248 - refacto immersion contact supprimer la table de jointure inutile
gip-inclusion/immersion-facile pull request #1380
Opened 2024-03-13 11:18 UTC by clement-duport

- add migration to remove joint table between establishment and contact and rename immersion contact table
- remove establishments immersion contact implementation

2024-03-13 15:26 UTC, JeromeBu requested changes

2024-03-13 15:26 UTC, JeromeBu commented on back/src/config/pg/kysely/model/database.ts
> +  siret: string | null;
Ca ne devrait pas être nullable

2024-03-13 15:26 UTC, JeromeBu commented on back/src/config/pg/migrations/1710248347259_remove-establishments-immersion-contacts-table.ts
> +    siret: { type: "char(14)", notNull: false },
ok mais il faut bien rentre non nullable une fois les données déplacés

2024-03-13 15:26 UTC, JeromeBu commented on back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.integration.test.ts
> +  // getAllEstablishmentImmersionContactsRows,
à supprimer

2024-03-13 15:34 UTC, mathildeburkard commented
C'est pour moi ça? Je comprends rien 🤣

On Wed, Mar 13, 2024, 16:27 Jérôme Burkard ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In back/src/config/pg/kysely/model/database.ts
> <https://github.com/gip-inclusion/immersion-facile/pull/1380#discussion_r1523462317>
> :
>
> > @@ -366,6 +360,7 @@ export interface ImmersionContacts {
>    phone: string | null;
>    contact_mode: ContactMode;
>    copy_emails: Generated<Json>;
> +  siret: string | null;
>
> Ca ne devrait pas être nullable
> ------------------------------
>
> In
> back/src/config/pg/migrations/1710248347259_remove-establishments-immersion-contacts-table.ts
> <https://github.com/gip-inclusion/immersion-facile/pull/1380#discussion_r1523472261>
> :
>
> > +
> +const oldContactsTableName = "immersion_contacts";
> +const newContactsTableName = "establishments_contacts";
> +
> +export async function up(pgm: MigrationBuilder): Promise<void> {
> +  // drop views
> +  pgm.dropMaterializedView("view_establishments_with_aggregated_offers");
> +  pgm.dropMaterializedView("view_establishments_with_flatten_offers");
> +  pgm.dropMaterializedView("view_establishments");
> +
> +  //rename table immersion contact
> +  pgm.renameTable(oldContactsTableName, newContactsTableName);
> +
> +  // add siret column and constraint to table establishment contacts
> +  pgm.addColumn(newContactsTableName, {
> +    siret: { type: "char(14)", notNull: false },
>
> ok mais il faut bien rentre non nullable une fois les données déplacés
> ------------------------------
>
> In
> back/src/domains/establishment/adapters/PgEstablishmentAggregateRepository.integration.test.ts
> <https://github.com/gip-inclusion/immersion-facile/pull/1380#discussion_r1523475725>
> :
>
> > @@ -30,7 +30,7 @@ import {
>  import { PgEstablishmentAggregateRepository } from "./PgEstablishmentAggregateRepository";
>  import {
>    InsertEstablishmentAggregateProps,
> -  getAllEstablishmentImmersionContactsRows,
> +  // getAllEstablishmentImmersionContactsRows,
>
> à supprimer
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/gip-inclusion/immersion-facile/pull/1380#pullrequestreview-1934483220>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A5GJH5O46HALJRTO4QUJHGLYYBV4TAVCNFSM6AAAAABET6ON2SVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSMZUGQ4DGMRSGA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-03-13 17:38 UTC, clement-duport commented on back/src/config/pg/kysely/model/database.ts
> +  siret: string | null;
yep je sais mais c'est qu'on a environ 500 contact qui n'ont pas d'équivalent dans la table de jointure du coup j'ai laisser comme ça en attendant demain de voir ce qu'on va faire de ces 500

2024-03-14 09:40 UTC, celineung commented on back/src/config/pg/migrations/1710248347259_remove-establishments-immersion-contacts-table.ts
> +    siret: { type: "char(14)", notNull: false },
je rajouterai bien le delete de ces 500 contacts dans cette PR

2024-03-14 17:24 UTC, JeromeBu commented on back/src/config/pg/migrations/1710248347259_remove-establishments-immersion-contacts-table.ts
> +    siret: { type: "char(14)", notNull: false },
Oui je pense que c'est le plus simple

2024-03-15 16:41 UTC, JeromeBu approved these changes

2024-03-18 12:13 UTC, merged