1554 dlgation partie 1 parcours sans dlgation
gip-inclusion/immersion-facile pull request #1561
Opened 2024-04-17 11:06 UTC by clement-duport

- add agency delegation contact email template
- create notify agency delegation contact usecase
- add delegation contact request route

2024-04-18 11:49 UTC, JeromeBu requested changes

2024-04-18 11:49 UTC, JeromeBu commented on back/src/adapters/primary/routers/technical/technicalRouter.e2e.test.ts
> +};
on a pas moyen d'avoir une version plus minimaliste pour éviter de charger le test avec autant de données qui gène la lisibilité ? (peut-être que la réponse est non...)

2024-04-18 11:49 UTC, JeromeBu commented on back/src/domains/convention/use-cases/notifications/NotifyAgencyDelegationContact.ts
> +};
peut-être moyen de faire un petit objet avec une validation zod ? 

2024-04-18 16:37 UTC, celineung commented on back/src/domains/convention/use-cases/notifications/NotifyAgencyDelegationContact.ts
> +};
@JeromeBu 
Si j'ai bien compris: il s'agirait alors de vérifier ici le format de la réponse Tally et si le formulaire contient bien toutes les questions/réponses attendues ?

Le TallyForm ressemble à ça:

```ts
export const tallyFormSchema = z
  .object({
    eventId: z.string(),
    eventType: z.string(),
    createdAt: z.string(),
    data: z.object({
      responseId: z.string(),
      submissionId: z.string(),
      respondentId: z.string(),
      formId: z.string(),
      formName: z.string(),
      createdAt: z.string(),
      fields: z.array(
        z.object({
          key: z.string(),
          label: z.string().nullable(),
          type: z.string(),
          value: z.any().nullable(),
          options: z
            .array(
              z.object({
                id: z.string(),
                text: z.string(),
              }),
            )
            .optional(),
        }),
      ),
    }),
  })
  .passthrough();
  ```

L'idée serait de rajouter un schéma dans ce genre pour pour la propriété `fields` ?

```ts
//pseudo-code
const expectedLabels: string = ["Nom", "Prénom", "Email", "Nom de la structure qui souhaite une convention de délégation", ...];

const fieldsSchema = z.array(z.object(...)).refine((fields) => {
  fields.every((field) => expectedLabels.includes(field.label))
})
```

2024-04-22 08:03 UTC, JeromeBu commented on back/src/domains/convention/use-cases/notifications/NotifyAgencyDelegationContact.ts
> +};
Je voulais dire un truc plus simple : 

```ts
const tallyContactDelegationFormFieldsSchema = z.object({
  "Nom": zStringMin1,
  "Prenom": zStringMin1,
  ...
  etc...
});

const tallyValidated = tallyContactDelegationFormFieldsSchema({
  "Nom": getTallyFormValueOf("Nom"),
  "Prenom": getTallyFormValueOf("Prénom"),
  ...
})
```

Je ne sais pas ce que ça vaut... Vous n'êtes pas obligé de suivre ce conseil...

2024-04-22 08:35 UTC, JeromeBu approved these changes

2024-04-22 08:50 UTC, merged