create migration file to store validator and counsellors as users and not in agencies table any more
gip-inclusion/immersion-facile pull request #1612
Opened 2024-05-02 12:55 UTC by JeromeBu

2024-05-15 10:37 UTC, celineung reviewed
- sur la review-app il n'est pas possible de se connecter sur le backoffice, je corrigerai cela dans une autre PR. Sinon fonctionnellement en local, ça a l'air ok

2024-05-15 10:37 UTC, celineung commented on front/src/app/components/forms/agency/EditAgencyForm.tsx
> +            label="!Statut de l'agence !"
je trouve que ça rend plus visible le warning avec l'icone

2024-05-15 12:31 UTC, celineung commented on back/src/domains/agency/adapters/PgAgencyRepository.ts
> +      );
suggestion:

```suggestion
      await Promise.all(
        [...agency.counsellorEmails.map(async (email) =>
          this.#addUserAndAgencyRights(email, agency.id, "counsellor"),
        ),
        ...agency.validatorEmails.map(async (email) =>
          this.#addUserAndAgencyRights(email, agency.id, "validator"),
        )]
      );
```

2024-05-15 12:31 UTC, celineung commented on back/src/domains/agency/adapters/PgAgencyRepository.ts
> +      // admin_emails: agency.adminEmails && JSON.stringify(agency.adminEmails),
supprimer ces commentaires

2024-05-15 12:31 UTC, celineung commented on front/src/app/components/forms/agency/EditAgencyForm.tsx
> +            label="!Statut de l'agence !"
je trouve que le warning est mieux visible avec l'ancienne icone

2024-05-15 12:32 UTC, celineung approved these changes

2024-05-16 09:20 UTC, JeromeBu commented on front/src/app/components/forms/agency/EditAgencyForm.tsx
> +            label="!Statut de l'agence !"
je pense que c'est biome qui m'a fait ça. Je vais rollback

2024-05-16 09:21 UTC, JeromeBu commented
> Sur la review-app je ne parviens pas à me connecter sur le backoffice, mais en local, tout marche bien.

je pense que inclusion connect, on a du leur passer un domaine. et sur les reviews app on est pas sur le bon domaine... enfin, à vérifier mais c'est ce qui me vient à l'esprit

2024-05-17 08:25 UTC, bbohec requested changes

2024-05-17 08:25 UTC, bbohec commented on back/src/domains/agency/use-cases/RegisterAgencyToInclusionConnectUser.ts
> +      uow.inclusionConnectedUserRepository.updateAgencyRights(user),
Proposition à inclure dans cette PR qui ajoutera pas mal de changement mais c'est juste du nommage:
renommer inclusionConnectedUserRepository en userRepository ?

Je crois que d'un point de vue PG la table se nomme déjà User?

2024-05-17 08:25 UTC, bbohec commented on back/src/domains/core/authentication/inclusion-connect/adapters/PgUserRepository.integration.test.ts
> +      );
```suggestion
      const response = await pgUserRepository.findByExternalId(userExternalId);
```

2024-05-17 08:25 UTC, bbohec commented on back/src/domains/core/dashboard/port/InclusionConnectedUserRepository.ts
> +  updateAgencyRights(user: InclusionConnectedUser): Promise<void>;
Cette méthode update a toujours étée utilisée pour mettre à jour que les droits d'agence ou bien elle était utilisée à un moment pour MAJ d'autres aspects d'un utilisateur?

Ca vaudrait pas le coup alors de fournir juste le userId et les agencyRights qu'on veut appliquer à l'utilisateur au lieu du `InclusionConnectedUser` complet ?

2024-05-17 08:25 UTC, bbohec commented on back/src/domains/core/authentication/inclusion-connect/adapters/agencyUsers.helpers.ts
> +    .execute();
On avait fait un pattern un peu plus sympa qui évite le `let` de souvenir dans le convention query pour les filtres optionnels avec du pipe. Ca te dis de partir sur la même approche?

2024-05-17 10:39 UTC, JeromeBu commented on front/src/app/components/forms/agency/EditAgencyForm.tsx
> +            label="!Code Safir de l'agence !"
yes un problème d'IDE qui se permet de faire des changements qu'on a pas demandé... 😅

2024-05-17 10:42 UTC, JeromeBu commented on back/src/domains/agency/adapters/PgAgencyRepository.ts
> +      );
étant donnée que dans cetrains cas il y a des dizaines de users dans chaque tableau, je préfère les faire en séquence. Le temps perdu est de quelques millisecondes, mais on a moins de risque de dépasser le nombre de connection à la db

2024-05-17 10:45 UTC, JeromeBu commented on back/src/domains/agency/use-cases/RegisterAgencyToInclusionConnectUser.ts
> +      uow.inclusionConnectedUserRepository.updateAgencyRights(user),
Il y a deux chose différentes :
le AuthenticatedUser qu'on peut renomer User partout. C'est un user tout seul.

Le inclusion connect User c'est un User (authenticated user) + plein de droits en tous genre (agence, etablissements etc...).

Donc ok pour renommer AuthenticatedUserRepository  en UserRepository. Pour la partie inclusion connect repo c'est différent. Peut-être qu'on peut trouver un meilleur nom, mais je pense que c'est mieux de faire ça dans une autre PR

2024-05-17 10:56 UTC, JeromeBu commented on back/src/domains/core/authentication/inclusion-connect/adapters/agencyUsers.helpers.ts
> +    .execute();
Je fais les modifs, mais j'ai l'impression que c'est plus lisible avec le `let`.

Je remets la version let ici pour comparaison :

```ts
 let builder = transaction
    .selectFrom("users__agencies")
    .innerJoin("users", "users.id", "users__agencies.user_id")
    .where("agency_id", "in", agencyIds)
    .where((eb) =>
      eb.or([eb("role", "=", "validator"), eb("role", "=", "counsellor")]),
    );

  if (isNotifiedByEmail !== undefined) {
    builder = builder.where("is_notified_by_email", "=", isNotifiedByEmail);
  }

  return builder
    .orderBy("users.email")
    .select([
      "users.id as userId",
      "users.email",
      "users__agencies.role",
      "users__agencies.agency_id as agencyId",
      "users__agencies.is_notified_by_email as isNotifiedByEmail",
    ])
    .execute();
    ```

2024-05-17 11:30 UTC, bbohec commented on back/src/domains/core/authentication/inclusion-connect/adapters/agencyUsers.helpers.ts
> +    .execute();
Je te fais une proposition pour simplifier encore un peu?
Quelque chose du style:

``` typescript
export const getUsersWithAgencyRole = async (
  transaction: KyselyDb,
  {
    agencyIds,
    isNotifiedByEmail,
  }: {
    agencyIds: AgencyId[];
    isNotifiedByEmail?: boolean;
  },
): Promise<UserWithAgencyRole[]> => {
  if (agencyIds.length === 0) return [];
  return pipeWithValue(
    transaction
    .selectFrom("users__agencies")
    .innerJoin("users", "users.id", "users__agencies.user_id")
    .where("agency_id", "in", agencyIds)
    .where((eb) =>
      eb.or([eb("role", "=", "validator"), eb("role", "=", "counsellor")]),
    )
    .orderBy("users.email")
    .select([
      "users.id as userId",
      "users.email",
      "users__agencies.role",
      "users__agencies.agency_id as agencyId",
      "users__agencies.is_notified_by_email as isNotifiedByEmail",
     ]),
    (builder) => isNotifiedByEmail !== undefined
      ? builder.where("is_notified_by_email", "=", isNotifiedByEmail);
      : builder;
    },
    (builder) =>builder.execute(),
  );
};
```

2024-05-17 11:45 UTC, bbohec approved these changes

2024-05-20 07:28 UTC, merged