wip : init notification slice
gip-inclusion/immersion-facile pull request #1636
Opened 2024-05-14 15:03 UTC by enguerranws

2024-06-03 08:52 UTC, bbohec approved these changes

2024-06-03 08:52 UTC, bbohec commented on front/src/app/pages/admin/technical-options-sections/ApiConsumersSection.tsx
> +    setCurrentApiConsumerToEdit(defaultApiConsumerValues(uuidV4()));
Il n'y a pas par conséquence un changement de l'Id du consumer en mode Edit?

2024-06-03 09:31 UTC, enguerranws commented on front/src/app/pages/admin/technical-options-sections/ApiConsumersSection.tsx
> +    setCurrentApiConsumerToEdit(defaultApiConsumerValues(uuidV4()));
Non, il y a une autre fonction qui gère le click sur un bouton d'édition.

2024-06-04 14:43 UTC, JeromeBu requested changes

2024-06-04 14:43 UTC, JeromeBu commented on front/src/app/components/notifications/NotificationFeedback.tsx
> +  return (
j'ai l'impression que l'option render n'est jamais utilisé dans la PR (en tout cas pas sur cmd + F '<NotificationFeedback' sur cette PR). Si ça ne sert pas, autant la virer.

2024-06-04 14:43 UTC, JeromeBu commented on front/src/app/pages/admin/technical-options-sections/ApiConsumersSection.tsx
>      dispatch(apiConsumerSlice.actions.clearFeedbackTriggered());
cette partie n'est pas supprimé au profit de la slice de feedback ?

2024-06-04 14:43 UTC, JeromeBu commented on front/src/core-logic/domain/notification/notification.slice.ts
> +export type NotificationLevel = "info" | "success" | "warning" | "error";
au niveau naming, j'ai une grosse preference pour feedback...

2024-06-04 14:51 UTC, enguerranws commented on front/src/app/components/notifications/NotificationFeedback.tsx
> +  return (
Je veux bien, mais on va en avoir besoin très vite (champs email avec vérif emailable par ex).

2024-06-04 14:52 UTC, enguerranws commented on front/src/app/pages/admin/technical-options-sections/ApiConsumersSection.tsx
>      dispatch(apiConsumerSlice.actions.clearFeedbackTriggered());
bonne question, je regarde

2024-06-04 14:53 UTC, enguerranws commented on front/src/core-logic/domain/notification/notification.slice.ts
> +export type NotificationLevel = "info" | "success" | "warning" | "error";
@bbohec @clement-duport @celineung On part sur Feedback ? moi ça me va aussi

2024-06-05 12:10 UTC, JeromeBu commented on front/src/app/components/notifications/NotificationFeedback.tsx
> +  return (
ah oui, OK 👍  alors gardons

2024-06-05 12:13 UTC, JeromeBu commented on front/src/core-logic/domain/apiConsumer/apiConsumer.test.ts
> +      });
👍  ca me va très bien de tester comme ça

2024-06-05 12:14 UTC, JeromeBu commented on front/src/app/components/notifications/NotificationFeedback.tsx
> +  render,
on a des résidu de `notification` ici

2024-06-05 12:14 UTC, JeromeBu commented on front/src/app/components/notifications/WithNotificationFeedbackReplacer.tsx
> +type NotificationFeedbackProps = {
et ici aussi

2024-06-05 12:14 UTC, JeromeBu commented on front/src/app/pages/admin/technical-options-sections/ApiConsumersSection.tsx
> +import { WithNotificationFeedbackReplacer } from "src/app/components/notifications/WithNotificationFeedbackReplacer";
on peut renommer le dossier entier d'ailleurs

2024-06-05 12:15 UTC, JeromeBu commented on front/src/core-logic/domain/feedback/feedback.slice.ts
> +const initialNotifications: Feedbacks = {};
```suggestion
const initialFeedbacks: Feedbacks = {};
```

2024-06-06 15:00 UTC, merged