TECH - rendre les données des seed plus fiables
gip-inclusion/immersion-facile pull request #1784
Opened 2024-06-14 15:17 UTC by celineung

2024-06-17 10:19 UTC, JeromeBu requested changes

2024-06-17 10:19 UTC, JeromeBu commented on back/src/scripts/seed.ts
> +    .withExternalId(new UuidV4Generator().new())
ca tu ne peux pas, le `externalId` doit rester fix, car c'est celui que nous retourne inclusion connect. Mais ca mérite de le mettre dans une variable bien nommé. L'ID je ne suis pas aussi sur... mais l'external ID, sur qu'il faut le conserver.

2024-06-17 10:19 UTC, JeromeBu commented on back/src/scripts/seed.ts
> +    .withExternalId(new UuidV4Generator().new())
idem

2024-06-18 16:30 UTC, celineung commented on back/src/scripts/seed.ts
> +      insertAgencySeed({ uow, kind: "pole-emploi" }),
il y a plusieurs insert ici, mais c'est rapide

2024-06-26 10:12 UTC, JeromeBu approved these changes

2024-06-27 10:21 UTC, merged