1697 lier une convention initie  partir dune mise en relation par les id de la mer et de la convention
gip-inclusion/immersion-facile pull request #1802
Opened 2024-06-18 11:12 UTC by JeromeBu

- **save conventionId linked to discussion, on addConvention**
- **fix frontend to fit with discussionId optionnaly provided to addConvention**
- **reorganise DiscussionDto**

2024-06-19 14:22 UTC, bbohec requested changes

2024-06-19 14:22 UTC, bbohec commented on back/src/domains/establishment/adapters/PgDiscussionRepository.integration.test.ts
On test la transition discussionId <> null au niveau des mises à jours dans le repo?

2024-06-19 14:22 UTC, bbohec commented on back/src/domains/establishment/use-cases/discussions/MarkDiscussionLinkedToConvention.ts
> +    if (discussion.siret !== convention.siret) return;
Pas d'erreur ici? D'un point de vue métier ça de devrait pas arriver.

2024-06-19 14:22 UTC, bbohec commented on back/src/domains/establishment/use-cases/discussions/MarkDiscussionLinkedToConvention.unit.test.ts
> +describe("MarkDiscussionLinkedToConvention", () => {
J'ai l'impression qu'il manque le test où on ne fourni pas `discussionId` dans le payload, c'est ici où on souhaite qu'il ne se passe rien.

Pour le cas où on ne retrouve pas la discussion je dirait erreur.
Pour le cas où le SIRET diffère.... je ne sais pas je dirais OSEF si le bénéficiaire a par exemple été redirigé sur une autre entreprise lors de la mise en relation

2024-06-19 14:22 UTC, bbohec commented on front/src/app/components/admin/establishments/DiscussionManageContent.tsx
> +      return connectedUser ? (
```suggestion
    .with(P.not(null), (discussion) =>  connectedUser ? (
```

2024-06-19 14:22 UTC, bbohec commented on shared/src/discussion/discussion.schema.ts
> +  conventionId: conventionIdSchema,
il manquerai pas optional?

2024-06-19 18:29 UTC, JeromeBu commented on back/src/domains/establishment/use-cases/discussions/MarkDiscussionLinkedToConvention.ts
> +    if (discussion.siret !== convention.siret) return;
Ça ne devrait pas mais c’est une route ouverte au public, c’est un Check coute pas cher et qui permet d’éviter que des petits malin fasse marquer des discussions qui n’ont rien à voir comme lié à une convention

2024-06-19 18:30 UTC, JeromeBu commented on shared/src/discussion/discussion.schema.ts
> +  conventionId: conventionIdSchema,
Si 👍

2024-06-19 18:31 UTC, JeromeBu commented on back/src/domains/establishment/adapters/PgDiscussionRepository.integration.test.ts
Non je crois pas

2024-06-19 18:32 UTC, JeromeBu commented on back/src/domains/establishment/use-cases/discussions/MarkDiscussionLinkedToConvention.unit.test.ts
> +describe("MarkDiscussionLinkedToConvention", () => {
Mais que fait-on de cette erreur ? Si rien alors autant juste ne rien faire. Sinon il faut savoir ce qu’on veut en faire. Peut être juste une alerte discord

2024-06-26 07:23 UTC, bbohec approved these changes

2024-06-26 07:23 UTC, merged