allowed validator user to validate convention and send modification request from backoffice
gip-inclusion/immersion-facile pull request #1830
Opened 2024-06-26 13:52 UTC by clement-duport

2024-06-26 14:28 UTC, JeromeBu requested changes

2024-06-26 14:28 UTC, JeromeBu commented on front/src/app/components/forms/convention/JustificationModalContent.tsx
>              },
on est pas dans le cas counsellor là ? 

2024-06-26 14:28 UTC, JeromeBu commented on front/src/app/components/admin/conventions/ConventionManageContent.tsx
> +          : ["backOffice", ...inclusionConnectedRoles],
c'est pas correct ça : "agencyOwner" n'est pas ni backoffice, ni validator

2024-06-26 16:29 UTC, clement-duport commented on front/src/app/components/forms/convention/JustificationModalContent.tsx
>              },
Justement ça je voulais en parler par ce que ici il peut avoir les deux et on a pas vraiment moyen de savoir en tant que "qui" il fait la demande

2024-06-27 08:34 UTC, JeromeBu approved these changes

2024-06-27 08:42 UTC, merged