1748 etq victor jai accs  des donnes dun tableau de bord metabase via lapi de metabase
gip-inclusion/immersion-facile pull request #1865
Opened 2024-07-04 20:57 UTC by JeromeBu

- **pagination modelisation**
- **change API consumer rights to be able to handle establishment stats endpoint**
- **create use case to Get Establishment stats**
- **implement postgres adapeter for establishment stats**

2024-07-09 10:14 UTC, bbohec requested changes

2024-07-09 10:14 UTC, bbohec commented on back/src/domains/core/statistics/adapters/PgStatisticQueries.ts
> +      .orderBy("siret")
Ici premier liant entre les domaines/contextes convention <> recherche au niveau base de donnée.

Ok pour un début mais niveau évolutivité de l'appli ça pose question.

2024-07-09 10:14 UTC, bbohec commented on back/src/domains/core/statistics/adapters/PgStatisticQueries.ts
> +      .executeTakeFirst()) ?? { totalRecords: 0 };
total records semble être calculé à partir des conventions uniquement.

Quid des entreprises qui n'ont pas fait de convention mais qui sont référencés comme entreprise accueillante.

On a pas le nombre de résultats disponible dans les métadonnées de la query du dessous?

Ca intéroge aussi sur l'usage du left join.

On pourrait avoir des résultats de type:
```
{
    siret: "354654654",
    numberOfConventions: 0,
    isReferenced: true
}
```

2024-07-09 10:14 UTC, bbohec commented on back/src/domains/core/statistics/adapters/PgStatisticQueries.integration.test.ts
Comme indiqué dans l'adapter, quid d'un établissement qui est référencé mais sans conventions

2024-07-09 10:14 UTC, bbohec commented on back/src/domains/core/statistics/adapters/InMemoryStatisticQueries.ts
> +    throw new Error("Method not implemented.");
Pourquoi non implémenté?

2024-07-09 10:14 UTC, bbohec commented on back/src/adapters/primary/routers/apiKeyAuthRouter/createApiKeyAuthRouter.v2.ts
> +  );
Pas de test e2e pour prouver le fonctionnement de la pagination?

2024-07-09 11:54 UTC, JeromeBu commented on back/src/domains/core/statistics/adapters/PgStatisticQueries.ts
> +      .executeTakeFirst()) ?? { totalRecords: 0 };
très bonne remarque, j'ai effectivement omis ce cas là. On doit pouvoir y arriver avec un full join. Je regarderai ça

2024-07-09 11:56 UTC, JeromeBu commented on back/src/domains/core/statistics/adapters/PgStatisticQueries.integration.test.ts
(yes idem précédent, il faut regarder)

2024-07-09 11:59 UTC, JeromeBu commented on back/src/adapters/primary/routers/apiKeyAuthRouter/createApiKeyAuthRouter.v2.ts
> +  );
yes, il faut, tu as raison

2024-07-09 12:00 UTC, JeromeBu commented on back/src/domains/core/statistics/ports/StatisticQueries.ts
> +  getEstablishmentStats(pagination: {
yes

2024-07-10 11:56 UTC, bbohec commented on back/src/domains/core/statistics/adapters/InMemoryStatisticQueries.ts
> +    throw new Error("Method not implemented.");
tu vas peut être avoir besoin de faire une implem pour les tests e2e quittes à fake les résultats attention et ne pas faire une implem trop intelligente qui nécessiterait le repo convention & establishmentAggregate. Juste pour simuler le cas passant.

2024-07-10 11:59 UTC, bbohec commented on back/src/domains/core/statistics/adapters/PgStatisticQueries.ts
> +      .orderBy("siret")
Perso c'est pas ma vision des choses, chaque contexte applicatif autonome devrait avoir exclusivement l'accès direct à ses repos.

Un contexte tiers ne devrait pas pouvoir y accéder mais plutôt passer par des API du domaine qui fourni les données.
Mais vu qu'on en est au début de cette réflexion qu'on a pas tous cette vision commune, OK pour démarrer comme ça quittes à rework la feature avec l'expérience.

2024-07-11 09:35 UTC, bbohec requested changes

2024-07-11 09:35 UTC, bbohec commented on shared/src/pagination/pagination.schema.ts
> +});
```suggestion

const pageQueryParamSchema = z.coerce.number().positive().min(1)  //Peut être ajouter .int() pour imposer un entier ?
const perPageQueryParamSchema = z.coerce.number().min(1).max(5_000)  //Peut être ajouter .int() pour imposer un entier ?

export const paginationQueryParamsSchema: z.Schema<PaginationQueryParams> =
  z.object({
    page: pageQueryParamSchema.optional(),
    perPage: perPageQueryParamSchema.optional(),
  });

export const paginationRequiredQueryParamsSchema: z.Schema<
  Required<PaginationQueryParams>
> = z.object({
  page: pageQueryParamSchema,
  perPage: perPageQueryParamSchema,
});
```

2024-07-11 09:39 UTC, bbohec approved these changes

2024-07-11 10:11 UTC, merged