prepare Broadcast button and modal
gip-inclusion/immersion-facile pull request #1878
Opened 2024-07-10 08:03 UTC by JeromeBu

2024-07-11 09:52 UTC, clement-duport commented on front/src/app/components/admin/conventions/ConventionManageActions.tsx
> +// };
Un oublis ou c'est pour plus tard ?

2024-07-11 09:52 UTC, clement-duport commented on front/src/app/components/admin/conventions/BroadcastAgainButton.tsx
> +const broadcastAgainButton = createModal({
Plutôt "broadcastAgainModal" non ?

2024-07-11 09:52 UTC, clement-duport commented on front/src/app/components/admin/conventions/BroadcastAgainButton.tsx
> +  // should check if agency has an API consumer which has subscriptions.
Ce commentaire tu le laisse pour le jour ou on implémentera cette feature pour les agences ?

2024-07-11 10:00 UTC, clement-duport requested changes
toto

2024-07-11 13:34 UTC, ClementLmd commented on front/src/app/components/admin/conventions/BroadcastAgainButton.tsx
> +  // should check if agency has an API consumer which has subscriptions.
Oui ce sera fait dans un deuxième temps.

2024-07-12 08:06 UTC, enguerranws commented on front/src/app/components/admin/conventions/BroadcastAgainButton.tsx
> +  return false;
Suggestion : 
`return apiConsumer.rights.convention.scope.agencyKinds?.includes(
      convention.agencyKind,
    ) ||     apiConsumer.rights.convention.scope.agencyIds?.includes(convention.agencyId)
  )`

2024-07-12 08:09 UTC, enguerranws approved these changes

2024-07-12 08:35 UTC, merged