#1797 - Modifier le rôle des utilisateurs en tant qu'admin
gip-inclusion/immersion-facile pull request #1951
Opened 2024-07-23 16:45 UTC by ClementLmd

A discuter:
- modification des données utilisateur dans:
  - une nouvelle page?
  - un nouvel onglet?
  - l'onglet "agences"?

2024-07-30 08:48 UTC, JeromeBu commented on front/src/core-logic/domain/admin/icUsersAdmin/icUsersAdmin.epics.ts
> +      (action: PayloadActionWithFeedbackTopic<IcUserRoleForAgencyParams>) =>
ce typage n'est pas necessaire , normalement tu en hérite directement grace au filter au dessus:

```suggestion
      (action) =>
```

2024-07-30 08:48 UTC, JeromeBu commented on front/src/core-logic/domain/admin/icUsersAdmin/icUsersAdmin.selectors.ts
> +const isUpdating = createSelector(
peut être plus explicite le nommage, car pas mal de choses peuvent s'updater :
```suggestion
const isUpdatingIcUserAgency = createSelector(
```

2024-07-30 08:48 UTC, JeromeBu commented on front/src/core-logic/domain/admin/icUsersAdmin/icUsersAdmin.selectors.ts
> +  isUpdating,
idem

2024-07-30 08:48 UTC, JeromeBu commented on front/src/core-logic/domain/admin/icUsersAdmin/icUsersAdmin.slice.ts
> +    updateUserOnAgencyRequested: (
je suis surpris de ne voir ça dans aucune Epic (ni autre...). Où est son usage ? Je le vois dispatché dans le form, mais comment réagit l'application ? 

2024-07-30 08:48 UTC, JeromeBu commented on front/src/app/components/agency/AgencyUsers.tsx
> +  id: "im-manage-user-modal",
j'ai ma réponse ça doit être "immersion"

2024-07-30 09:57 UTC, ClementLmd commented on front/src/app/components/agency/AgencyUsers.tsx
> +  id: "im-manage-user-modal",
ajout d'un id dans domElementIds

2024-07-30 10:05 UTC, ClementLmd commented on front/src/app/components/agency/AgencyUsers.tsx
> +type AgencyRoleClasses = {
pris en compte

2024-07-30 10:06 UTC, ClementLmd commented on front/src/core-logic/domain/admin/icUsersAdmin/icUsersAdmin.epics.ts
> +      (action: PayloadActionWithFeedbackTopic<IcUserRoleForAgencyParams>) =>
pris en compte

2024-07-30 10:06 UTC, ClementLmd commented on front/src/core-logic/domain/admin/icUsersAdmin/icUsersAdmin.selectors.ts
> +const isUpdating = createSelector(
pris en compte

2024-07-30 13:34 UTC, JeromeBu approved these changes

2024-07-31 07:21 UTC, enguerranws requested changes

2024-07-31 07:21 UTC, enguerranws commented on playwright/tests/admin/manageUser.spec.ts
> +    await page.getByRole("button", { name: "Modifier" }).click();
Ça, c'est beaucoup trop large. Il faut un sélecteur plus spécifique sinon il va péter rapidement.

2024-07-31 07:21 UTC, enguerranws commented on playwright/tests/admin/manageUser.spec.ts
> +    await expect(
à passer dans domElementIds

2024-07-31 08:02 UTC, ClementLmd commented on playwright/tests/admin/manageUser.spec.ts
> +    await expect(
fait, l'id était créé mais pas utilisé dans le test

2024-07-31 08:03 UTC, ClementLmd commented on playwright/tests/admin/manageUser.spec.ts
> +    await page.getByRole("button", { name: "Modifier" }).click();
remplacé par : `[id^=${domElementIds.admin.agencyTab.editAgencyUserRoleButton}]`

2024-07-31 12:36 UTC, merged