#1912 - Rattraper les mails de bilans qui n'ont pas été envoyés
gip-inclusion/immersion-facile pull request #1975
Opened 2024-07-26 10:05 UTC by celineung

==> merger la PR https://github.com/gip-inclusion/immersion-facile/pull/1970 avant

2024-07-29 10:32 UTC, bbohec requested changes

2024-07-29 10:32 UTC, bbohec commented on back/src/domains/establishment/use-cases/SendBeneficiariesAssesmentsEmails.unit.test.ts
> +    const now = timeGateway.now();
Tu as besoin de redéclarer now ici?

2024-07-29 10:32 UTC, bbohec commented on back/src/domains/establishment/use-cases/SendBeneficiariesPdfAssessmentsEmails.ts
> +    }),
Quittes à faire un schema avec ça, tu penses quoi de rajouter un refine qui s'assure que `from` est bien avant `to`. Pour éviter les bugs.

2024-07-29 10:32 UTC, bbohec commented on back/src/domains/establishment/use-cases/SendEmailsWithAssessmentCreationLink.ts
> +    }),
Vu qu'on l'utilise plusieurs fois, ça te dis de créer un dateRangeSchema unique avec la règle de refine proposée dans l'autre commentaire?

2024-07-29 10:32 UTC, bbohec commented on back/src/scripts/utils.ts
> +  }
Tu penses quoi de quelque chose du style:

```suggestion
 const result = futurDateRangeSchema({from:args[0] , to:args[1]}).safeParse()
 
 if (!result.isValid) {
    logger.error({ message: errorMessage });
    throw new Error(errorMessage);
 }
 return result.value
```

Quand à l'erreur "La date de fin doit être au plus tard à aujourd'hui.", je me pose la question si ça n'est pas une règle de gestion qu'on peut mettre dans le usecase pour empêcher d'envoyer les bilans trop tôt.

2024-07-29 12:04 UTC, celineung commented on back/src/domains/establishment/use-cases/SendBeneficiariesAssesmentsEmails.unit.test.ts
> +    const now = timeGateway.now();
now n'est pas déclaré dans le contexte de ce test

2024-07-30 13:06 UTC, bbohec approved these changes

2024-07-31 10:53 UTC, merged