Establishment & Agency new wording
gip-inclusion/immersion-facile pull request #2006
Opened 2024-08-01 09:49 UTC by chaibax

Amélioration des textes et ajout d'un lien vers l'inscirption a un webinaire. 

<img width="1328" alt="Capture d’écran 2024-08-01 à 11 45 35" src="https://github.com/user-attachments/assets/7a63537a-874a-4215-80fa-ccc58860d042">
<img width="1324" alt="Capture d’écran 2024-08-01 à 11 45 27" src="https://github.com/user-attachments/assets/7344b713-4f36-4e41-bc13-4ef9c8146243">
![Capture d’écran 2024-07-23 à 14 13 04](https://github.com/user-attachments/assets/a6adbc8d-923c-455a-87fe-0add04dfefc0)

2024-08-01 12:19 UTC, enguerranws requested changes
👍 tu peux juste nettoyer les commits ? (supprimer les commits de wip)

2024-08-01 15:36 UTC, JeromeBu commented
je viens de rebase et squasher les commits

2024-08-01 15:37 UTC, JeromeBu approved these changes

2024-08-02 12:04 UTC, enguerranws approved these changes

2024-08-05 07:28 UTC, celineung commented on front/src/app/contents/home/content.ts
> +        "Régulèrement, nous organisons des webinaire en ligne pour vous présenter l'immersions professionnelles, notre plateforme, et répondre à vos questions. Cliquez-ici pour vous inscrire à la pro
```suggestion
        "Régulièrement, nous organisons des webinaire en ligne pour vous présenter l'immersions professionnelles, notre plateforme, et répondre à vos questions. Cliquez-ici pour vous inscrire à la prochaine séssions",
```

2024-08-05 07:28 UTC, celineung commented on front/src/app/contents/home/content.ts
> +      badgeLabel: "Féxible",
```suggestion
      badgeLabel: "Fléxible",
```

2024-08-05 07:33 UTC, enguerranws commented on front/src/app/contents/home/content.ts
> +      title: "Qui peut prescrire une immersion?",
```suggestion
      title: "Qui peut prescrire une immersion ?",
```

2024-08-05 08:01 UTC, enguerranws commented on front/src/app/contents/home/content.ts
> +        "Les prescripteurs de droits commun (France Travail, Missions Locales, Cap emploi, Conseil Départemental, CEP, SIAE sauf ETTI et prépa apprentissage) et tous les professionnels de l'accompagn
```suggestion
        "Les prescripteurs de droit commun (France Travail, Missions Locales, Cap emploi, Conseil Départemental, CEP, SIAE sauf ETTI et prépa apprentissage) et tous les professionnels de l'accompagnement qui peuvent avoir une délégation auprès des prescripteurs de droit commun.",
```

2024-08-05 11:46 UTC, merged