1996 sur une agence prescriptrice sans double validation il y a un conseiller
gip-inclusion/immersion-facile pull request #2073
Opened 2024-08-08 13:38 UTC by clement-duport

- remove counsellor option when agency is only one step validation
- throw an error if trying to update user right with role counsellor for agency with only one step validation
- change default role for user from counsellor to agency viewer

2024-08-08 14:50 UTC, celineung commented on shared/src/errors/errors.ts
> +        `Le role "${role}" n'est pas autorisé pour l'agence "${agencyId}" car cette agence n'a qu'une seul étape de validation.`,
```suggestion
        `Le role "${role}" n'est pas autorisé pour l'agence "${agencyId}" car cette agence n'a qu'une seule étape de validation.`,
```

2024-08-08 14:50 UTC, celineung commented on back/src/domains/inclusion-connected-users/use-cases/UpdateIcUserRoleForAgency.unit.test.ts
> +    const agency = new AgencyDtoBuilder()
ici le test vérifie que l'on ne peut pas supprimer le dernier utilisateur

2024-08-09 14:53 UTC, bbohec requested changes

2024-08-09 14:53 UTC, bbohec commented on back/src/adapters/primary/routers/admin/adminRouter.e2e.test.ts
> +            "Le role \"counsellor\" n'est pas autorisé pour l'agence \"aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa\" car cette agence n'a qu'une seul étape de validation.",
utiliser notre bibliotheque errors

2024-08-09 14:53 UTC, bbohec commented on back/src/domains/inclusion-connected-users/use-cases/UpdateIcUserRoleForAgency.ts
> +      });
Peut être pas à faire maintenant mais je proposerai bien counsellorEmails en optionnel / undefined si l'agence passe à un niveau de validation
Plutôt que de juste gérer la taille du tableau

2024-08-09 14:53 UTC, bbohec commented on back/src/domains/inclusion-connected-users/use-cases/UpdateIcUserRoleForAgency.unit.test.ts
> +    agencyRepository = uow.agencyRepository;
```suggestion
    agencyRepository = uow.agencyRepository;
```

2024-08-09 14:53 UTC, bbohec commented on back/src/config/pg/migrations/1723126978255_remove-counsellor-rights-on-users.ts
> +    WHERE users__agencies.user_id = usersToUpdate.user_id and users__agencies.agency_id = usersToUpdate.agency_id
```suggestion
    WITH 
    agenciesWithTwoStepsValidation as (
      SELECT agency_id
      FROM "users__agencies"
      WHERE roles::text LIKE '%counsellor%'
      AND is_notified_by_email IS true
    ), 
    usersToUpdate as (
      SELECT user_id, agency_id
      FROM "users__agencies"
      WHERE roles::text LIKE '%counsellor%'
      AND agency_id NOT IN (
        SELECT * 
        FROM agenciesWithTwoStepsValidation
      )
    )
    UPDATE users__agencies
    SET roles = '["agency-viewer"]'::jsonb
    FROM usersToUpdate
    WHERE users__agencies.user_id = usersToUpdate.user_id 
    AND users__agencies.agency_id = usersToUpdate.agency_id
```
C'est juste de la mise en forme pour mieux comprendre l'intention.
Peut être renommer usersToUpdate en userRightsOnAgenciesWithOneStepValidation

Mais attention avec cette query, il faut bien s'assurer de son comportement sinon on défonce les droits de plein de monde.

2024-08-09 14:56 UTC, bbohec requested changes
Tu as les tests playwright KO aussi

2024-08-12 08:49 UTC, bbohec approved these changes

2024-08-12 09:22 UTC, merged