reset tutor info when establishment representativ is different than tutor
gip-inclusion/immersion-facile pull request #2440
Opened 2024-10-30 11:05 UTC by clement-duport

2024-10-30 11:12 UTC, JeromeBu requested changes

2024-10-30 11:12 UTC, JeromeBu commented on front/src/app/components/forms/convention/sections/establishment/EstablishmentFormSection.tsx
> +                }
attention ici, pour moi c'est l'inverse : quand tu cliques sur : "non, ce ne sont pas les même" il faut vider les champs. S'il clique sur oui, il faut au contraire les aligner (et ne pas le montrer à l'utilisateur)

2024-10-30 12:27 UTC, clement-duport commented on front/src/app/components/forms/convention/sections/establishment/EstablishmentFormSection.tsx
> +                }
C'est mon nommage qui n'est pas claire. En fait ic je check que leur infos sont identique alors je reset les champs du tuteur.

2024-11-06 09:16 UTC, JeromeBu approved these changes

2024-11-06 10:22 UTC, merged