wip
gip-inclusion/immersion-facile pull request #2459
Opened 2024-10-31 16:38 UTC by clement-duport

2024-11-06 10:12 UTC, JeromeBu requested changes

2024-11-06 10:12 UTC, JeromeBu commented on front/src/app/components/forms/commons/AgencySelector.tsx
> +            ...register(agencyKindFieldName),
c'est necessaire le mémo ? on ne peut pas faire ça :

```suggestion
            ...register(agencyKindField.name),
```

2024-11-06 10:12 UTC, JeromeBu commented on front/src/app/components/forms/convention/ConventionForm.tsx
> +      "levelOfEducation" in convention.signatories.beneficiary
cette deuxième condition me parait pas nécessaire non ? 

Et je vois que les deux conditions renvoie le même type, ce qui me parait bizarre.

Je pense que des trucs de ce genre peuvent t'aider :

```ts
const isImmersionConvention = (
    convention: ConventionDto,
  ): convention is Extract<ConventionDto, { internshipKind: "immersion" }> => convention.internshipKind === "immersion"

const isMiniStage = (
    convention: ConventionDto,
  ): convention is Extract<ConventionDto, { internshipKind: "mini-stage-cci" }> => convention.internshipKind === "mini-stage-cci"
```

2024-11-06 10:12 UTC, JeromeBu commented on front/src/app/components/forms/convention/ConventionForm.tsx
> +              }
Tu doit pouvoir virer un niveau de fonction :
```suggestion
              onSubmit={handleSubmit(onSubmit, (errors) => {
                  validateSteps("doNotClear");
                  console.error(conventionValues, errors);
                })
              }
```

2024-11-06 10:12 UTC, JeromeBu commented on front/src/app/components/forms/convention/ConventionForm.tsx
> +                  type="submit"
tu es sur de toi là ? je pense pas qu'on soumette ici.... c'est juste pour passer à la page de vérification

2024-11-06 10:18 UTC, clement-duport commented on front/src/app/components/forms/commons/AgencySelector.tsx
> +            ...register(agencyKindFieldName),
Nope sinon on a un problème au niveau du typage

2024-11-06 10:26 UTC, clement-duport commented on front/src/app/components/forms/convention/ConventionForm.tsx
> +                  type="submit"
Si ici la soumission fait juste passer a la vérification

2024-11-12 10:23 UTC, JeromeBu approved these changes

2024-11-12 19:56 UTC, JeromeBu commented on front/src/app/components/forms/convention/conventionHelpers.ts
> +      agencyKind: agencyKindSchema,
Est-ce que ça suffirait pas ça (pour fixer ce qu'on a vu tout à l'heure) :

```suggestion
      agencyKind: agencyKindSchema.optional(),
```

2024-11-13 10:48 UTC, clement-duport commented on front/src/app/components/forms/convention/conventionHelpers.ts
> +      agencyKind: agencyKindSchema,
nope ça suffit pas

2024-11-14 10:59 UTC, JeromeBu approved these changes

2024-11-14 12:03 UTC, merged