fetch external search result from backend
gip-inclusion/immersion-facile pull request #2573
Opened 2024-11-20 16:11 UTC by enguerranws

2024-11-21 13:29 UTC, JeromeBu commented on front/src/core-logic/domain/search/search.test.ts
> +    // })
on vire ? ou on décommente ?

2024-11-22 16:24 UTC, bbohec requested changes

2024-11-22 16:24 UTC, bbohec commented on back/src/domains/establishment/adapters/la-bonne-boite/HttpLaBonneBoiteGateway.manual.test.ts
> +        .withEmployeeRange(0, 0)
```suggestion
      romeLabel: boulangerRomeData.romeLabel,
    });
    expectToEqual(result,
      new LaBonneBoiteCompanyDtoBuilder()
        .withName("L'ENTREMETS GOURMAND")
        .withSiret(siret)
        .withEmployeeRange(0, 0)
```

2024-11-22 16:24 UTC, bbohec commented on back/src/domains/establishment/adapters/la-bonne-boite/HttpLaBonneBoiteGateway.manual.test.ts
> +        .withEmployeeRange(0, 0)
Tu ne peux pas utiliser ici le même LBB Dto pour éviter de le refaire?

2024-11-22 16:28 UTC, bbohec requested changes

2024-11-22 16:28 UTC, bbohec commented on front/src/app/pages/search/SearchResultPage.tsx
Aucune autre modif sur SearchResultPage en mode external vs resultat à nous?

Tu as un exemple de la page avec un résultat LBB?

2024-11-25 08:22 UTC, enguerranws commented on front/src/app/pages/search/SearchResultPage.tsx
Non, la différence entre les deux était déjà gérée, c'est la provenance des données qui change

2024-11-25 09:08 UTC, merged