2441 etq admin agence je peux voir le tableau des agences sur lequelles je suis administrateur dagence et modifier leurs infos
gip-inclusion/immersion-facile pull request #2603
Opened 2024-11-26 12:41 UTC by clement-duport

- add agency dashboard slice epic selectors and test
- implement new methode in agency gateway
- implement new routes (front)
- add get agency by id for dashboard usecase
- update get inclusion conected users usecase to authorize agency admin
- add new routes in agency router (back)

2024-12-09 14:29 UTC, bbohec requested changes

2024-12-09 14:29 UTC, bbohec commented on front/src/core-logic/domain/agencies/create-user-on-agency/createUserOnAgency.epics.ts
> +                  {} as Record<AgencyId, AgencyRight>,
```suggestion
                agencyRights: user.agencyRights.reduce<Record<AgencyId, AgencyRight>>(
                  (agenciesAcc, agencyRight) => ({
                    ...agenciesAcc,
                    [agencyRight.agency.id]: agencyRight,
                  }),
                  {},
```

2024-12-09 14:29 UTC, bbohec commented on front/src/app/components/agency/AgencyUsersTable.tsx
> +      routeName === "adminAgencies" || routeName === "adminAgencyDetail"
Réduire la duplication pour avoir quelque chose du type

```typescript
const mode = routeName === "adminAgencies" || routeName === "adminAgencyDetail" ? domElementIds.admin.agencyTab : domElementIds.agencyDashboard.agencyDetails
```

Pour ensuite faire 
```typescript
[mode].agencyUsersTable
```

2024-12-09 14:29 UTC, bbohec commented on front/src/app/components/agency/AgencyUsers.tsx
> +        );
Rajouter une TODO pour retirer icUsersAdminSlice ou unifier au max dans updateUserOnAgencySlice

2024-12-10 11:19 UTC, celineung commented on back/src/domains/agency/use-cases/GetAgencyById.unit.test.ts
> +    ])
je n'ai pas compris la suggestion: pourquoi supprimer cette affectation de droit ?

2024-12-11 21:26 UTC, bbohec requested changes

2024-12-11 21:26 UTC, bbohec commented on back/src/domains/agency/use-cases/GetAgencyById.unit.test.ts
> +    ])
Les droits d'agence ne sont plus portés par les utilisateurs mais par les agences, il faut ajouter ce droit au niveau des fonctions `toAgencyWithRights(agencyWithRefersTo,...)` pour ajouter les droits dans le repo le temps qu'on transforme AgencyDto.

2024-12-12 09:21 UTC, celineung commented on back/src/domains/agency/use-cases/UpdateAgency.unit.test.ts
> +        },
ce test est déjà présent dans ce fichier

2024-12-12 10:39 UTC, celineung commented on back/src/domains/inclusion-connected-users/use-cases/RemoveUserFromAgency.unit.test.ts
> +    .withIsAdmin(false);
celui-ci est bien correct

2024-12-12 10:40 UTC, celineung commented on back/src/domains/inclusion-connected-users/use-cases/RemoveUserFromAgency.unit.test.ts
> +    .withIsAdmin(false);
mais il manque un cas dans la suite de test pour l'agency-admin

2024-12-12 11:06 UTC, celineung commented on back/src/domains/inclusion-connected-users/use-cases/UpdateUserForAgency.unit.test.ts
on a déjà ce test "throws forbidden if user to delete has not rights on agency"

2024-12-12 11:33 UTC, celineung commented on front/src/core-logic/domain/agencies/update-user-on-agency/updateUserOnAgency.epic.ts
> +              ...action.payload,
on a besoin de le destructurer pour passer aussi le feedbackTopic :

```
{
  ...action.payload,
  feedbackTopic: action.payload.feedbackTopic,
}
```

2024-12-12 13:45 UTC, celineung commented on front/src/app/components/agency/AgencyUsersTable.tsx
> +      routeName === "adminAgencies" || routeName === "adminAgencyDetail"
Je trouve la suggestion moins lisible.
Par contre j'ai remonté la logique en dehors du template pour l'alléger.

2024-12-12 13:46 UTC, celineung commented on front/src/app/components/agency/AgencyUsersTable.tsx
> +      routeName === "adminAgencies" || routeName === "adminAgencyDetail"
ça donne:

```ts
const id =
    routeName === "adminAgencies" || routeName === "adminAgencyDetail"
      ? domElementIds.admin.agencyTab.agencyUsersTable
      : domElementIds.agencyDashboard.agencyDetails.agencyUsersTable;
```

puis dans le template, simplement mettre `id={id}`

2024-12-13 09:53 UTC, celineung commented on back/src/domains/inclusion-connected-users/use-cases/UpdateUserForAgency.unit.test.ts
ce test existe, c'est "throws forbidden if user who isn't IF admin or agency admin attempts to update another user email"

2024-12-13 12:27 UTC, bbohec approved these changes

2024-12-16 08:43 UTC, merged