added button to resend edit establishment link in ErrorBoundary component
gip-inclusion/immersion-facile pull request #2613
Opened 2024-11-27 14:58 UTC by enguerranws

2024-11-27 15:56 UTC, bbohec requested changes

2024-11-27 15:56 UTC, bbohec commented on front/src/app/pages/error/ErrorPageContent.tsx
> +  return "jwt" in route.params;
```suggestion
const routeContainsJwt = (
  route: Route<typeof routes>,
): route is Route<typeof routes.editFormEstablishment> =>"jwt" in route.params
```

2024-11-27 15:56 UTC, bbohec commented on front/src/app/pages/establishment/RenewEstablishmentMagicLinkButton.tsx
> +};
Le bouton existait pas dans la modale?
Je ne vois pas la modale réutiliser ce nouveau composant

2024-11-27 16:01 UTC, JeromeBu requested changes

2024-11-28 15:25 UTC, bbohec approved these changes

2024-12-03 09:38 UTC, JeromeBu approved these changes

2024-12-03 09:38 UTC, merged