implement WithCache (Redis as an option)
gip-inclusion/immersion-facile pull request #2653
Opened 2024-12-03 15:24 UTC by JeromeBu

2024-12-13 12:31 UTC, JeromeBu commented on back/src/config/bootstrap/createGateways.ts
> +
deformation professionel, c'est un pattern que je vois souvent sur l'autre projet ou je bosse. Vous me dites si ca vous va. Sinon on fait en deux étapes :

```ts
const getWithCache = () => {...}
const withCache= getWithCache();
```

2024-12-13 14:18 UTC, bbohec requested changes

2024-12-13 14:29 UTC, JeromeBu commented on back/src/config/bootstrap/appConfig.ts
> +  }
ah mais je préfère que ca crash perso. Comme ça tu peux pas démarrer avec un oubli. C'est dans un getter. Donc ça ne sera appelé que si c'est utilisé

2024-12-13 14:29 UTC, JeromeBu commented on back/src/config/bootstrap/createGateways.ts
> +};
ok, je te mets ça dans un autre module

2024-12-13 14:29 UTC, JeromeBu commented on back/src/domains/core/address/adapters/HttpAddressGateway.ts
> +      },
c'est ce que je fais un peu plus loin, c'était pour minimiser le nombre de paramètre à fournir. Tu peux le voir dans l'implémentation Redis.

2024-12-13 14:29 UTC, JeromeBu commented on back/src/domains/core/caching-gateway/port/WithCache.ts
> +}) => Cb;
le any est uniquement dans le extend du générique. C'est juste que `Cb` doit valider `(...params: any[]) => Promise<any>>`

2024-12-13 14:35 UTC, JeromeBu commented on back/src/domains/core/caching-gateway/adapters/makeRedisWithCache.ts
> +          const response = JSON.parse(cachedValue);
je sais pas... mais ici les try catch sont necessaire pour "absorber" les erreurs. C'est à dire, tant pis on continue sans cache

2024-12-13 14:43 UTC, JeromeBu commented on back/src/domains/core/caching-gateway/adapters/makeRedisWithCache.ts
> +    }) as Callback;
malheureusment ça ne suffit pas....

2024-12-16 08:50 UTC, bbohec approved these changes

2024-12-16 09:42 UTC, celineung commented on back/src/config/bootstrap/cache.ts
> +  // Handle disconnections
pour moi, ce ne sont pas des commentaires nécessaires

2024-12-16 09:42 UTC, celineung commented on back/src/domains/core/caching-gateway/adapters/makeRedisWithCache.integration.test.ts
> +  it("calls the function the first time than gets results from cache", async () => {
```suggestion
  it("calls the function the first time then gets results from cache", async () => {
```

2024-12-16 10:33 UTC, enguerranws commented on back/src/domains/core/address/adapters/HttpAddressGateway.ts
> +        partner: "openCageData",
```suggestion
        partner: partnerNames.openCageData
```

2024-12-16 10:33 UTC, enguerranws commented on back/src/domains/core/caching-gateway/adapters/makeRedisWithCache.integration.test.ts
> +  });
On test pas le fait que la donnée expire bien au moment prévu ?

2024-12-16 10:36 UTC, JeromeBu commented on back/src/domains/core/address/adapters/HttpAddressGateway.ts
> +        partner: "openCageData",
si tu veux mais c'est typé, on ne peux pas se planter (c'est : `keyof typeof partnerNames`)

2024-12-16 10:38 UTC, enguerranws approved these changes

2024-12-16 10:46 UTC, merged