Tech - Refacto feedback slice
gip-inclusion/immersion-facile pull request #2655
Opened 2024-12-03 15:51 UTC by enguerranws

2024-12-09 09:55 UTC, bbohec requested changes

2024-12-09 09:55 UTC, bbohec commented on front/src/app/hooks/siret.hooks.ts
> +  // );
```suggestion

```

2024-12-09 09:55 UTC, bbohec commented on front/src/core-logic/domain/siret/siret.slice.ts
> +    ) => {
```suggestion
    siretModified: (
      state,
      action: PayloadActionWithFeedbackTopic<{ siret: SiretDto}>,
    ) => {
```

2024-12-09 09:55 UTC, bbohec commented on front/src/core-logic/domain/siret/siret.slice.ts
> +    ) => {
```suggestion
    siretInfoRequested: (
      state,
      _action: PayloadActionWithFeedbackTopic<{ siret: SiretDto}>,
    ) => {
```

2024-12-09 09:55 UTC, bbohec commented on front/src/core-logic/domain/establishment/establishment.test.ts
> +        } as SiretEstablishmentDto,
Tu as essayé de retiré le `as`?

2024-12-09 09:55 UTC, bbohec commented on front/src/core-logic/domain/establishment/establishment.slice.ts
> +      // };
```suggestion

```

2024-12-09 09:55 UTC, bbohec commented on front/src/core-logic/domain/establishment/establishment.slice.ts
> +      // state.feedback = { kind: "deleteSuccess" };
```suggestion

```

2024-12-09 09:58 UTC, celineung commented on front/src/core-logic/domain/feedback/feedback.slice.ts
> +  "search-result-page",
pour détacher la notion de "page":

```suggestion
  "search-result",
```

2024-12-09 09:58 UTC, celineung commented on front/src/app/hooks/siret.hooks.ts
> +  // );
à supprimer

2024-12-09 09:58 UTC, celineung commented on front/src/core-logic/domain/discussion/discussion.selectors.ts
> +  fetchError: createSelector(discussionState, ({ fetchError }) => fetchError),
je crois qu'il y a eu un loupé dans le commit: c'était à supprimer non ?

2024-12-09 09:59 UTC, celineung commented
Problème lors de la recherche (j'avais commencé à écrire "test" dans le métier à rechercher:
![Screenshot 2024-12-09 at 10 58 02](https://github.com/user-attachments/assets/a530bae9-00a5-4f94-bc1b-2db9e71bfab4)

2024-12-09 13:18 UTC, enguerranws commented
> Problème lors de la recherche (j'avais commencé à écrire "test" dans le métier à rechercher: ![Screenshot 2024-12-09 at 10 58 02](https://private-user-images.githubusercontent.com/11294487/393788889-a530bae9-00a5-4f94-bc1b-2db9e71bfab4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NTAyMjMsIm5iZiI6MTczMzc0OTkyMywicGF0aCI6Ii8xMTI5NDQ4Ny8zOTM3ODg4ODktYTUzMGJhZTktMDBhNS00Zjk0LWJjMWItMmRiOWU3MWJmYWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDEzMTIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYzU2NzIzNTdjOTQ4YzBhNjVjOTcxMGMyYjQzZDkyODkwZDFlYjgxODgyNDBkMmRhMDIyMzZmMGIwMjg4NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gDm6lh2nagS0Pzfvx2r77YVdqpIJEzC7Jj_ioTiQK2k)

Alors oui, mais ce n'est pas lié à cette PR je pense.

2024-12-10 10:24 UTC, bbohec approved these changes

2024-12-10 10:24 UTC, merged