#2578 - MAJ de la signature dans le resumé de la convention juste après la signature
gip-inclusion/immersion-facile pull request #2682
Opened 2024-12-05 19:54 UTC by JeromeBu

2024-12-09 09:17 UTC, bbohec requested changes

2024-12-09 09:17 UTC, bbohec commented on front/src/core-logic/domain/convention/convention.slice.ts
> +      };
On de devrait pas plutôt aller récupérer la convention signée dans le back une fois la signature en succès?

Peut être avec un extra sur la slice de convention qui va récupérer la convention sur l'événement signConventionSucceeded.
Ca n'empêche pas d'avoir isLoading à false et feedback success

2024-12-09 09:17 UTC, bbohec commented on front/src/core-logic/domain/convention/convention.test.ts
> +        .build() as ConventionReadDto;
```suggestion
      const convention = new ConventionDtoBuilder()
        .signedByEstablishmentRepresentative(new Date().toISOString())
        .buildRead(agency);
```

2024-12-09 09:17 UTC, bbohec commented on front/src/core-logic/domain/convention/convention.test.ts
> +        },
```suggestion
        convention: {
          ...convention,
          signatories: {
            ...convention.signatories,
            establishmentRepresentative: {
              ...convention.signatories.establishmentRepresentative,
              signedAt: new Date().toIsoString(),
            },
          },
        },
```
```suggestion
        convention: {
          ...convention,
          signatories: {
            ...convention.signatories,
            establishmentRepresentative: {
              ...convention.signatories.establishmentRepresentative,
              signedAt: expect.any(String),
            },
          } as Signatories,
        },
```

2024-12-10 10:39 UTC, JeromeBu commented on front/src/core-logic/domain/convention/convention.test.ts
> +        },
ici ca ne va pas le faire, car je ne maitrise pas le date.now. J'ai l'impression que tu as édité. Tu me dis si on peut cloturer ce cas. Le `as Signatories` est malheureusement necessaire (pour des histoires de type de convention)

2024-12-10 11:03 UTC, bbohec approved these changes

2024-12-10 12:10 UTC, bbohec commented on front/src/core-logic/domain/convention/convention.epics.ts
> +    ),
Pas besoin de changer cette partie j'ai l'impression

2024-12-10 12:11 UTC, bbohec commented on front/src/core-logic/domain/convention/convention.epics.ts
> +    ),
On peut pas throw avant d'enclancher l'action si on a pas de convention/token de dispo plutôt que d'envoyer des chaines vide et faire du as sur le token?

2024-12-10 12:23 UTC, JeromeBu commented on front/src/core-logic/domain/convention/convention.epics.ts
> +    ),
le as sur le token est pour le cas PeConnect (qui passe par là aussi). On peut toujours throw en amont. Je comptais laisser le back nous dire ce qui ne vas pas

2024-12-10 13:42 UTC, bbohec approved these changes

2024-12-10 13:43 UTC, merged