add business address and business name to severals emails template
gip-inclusion/immersion-facile pull request #314
Opened 2023-06-15 10:41 UTC by clement-duport

Liste des templates modifiés :  

NEW_ESTABLISHMENT_CREATED_CONTACT_CONFIRMATION,
EDIT_FORM_ESTABLISHMENT_LINK,
SUGGEST_EDIT_FORM_ESTABLISHMENT,
CONTACT_BY_EMAIL_REQUEST

2023-06-15 10:44 UTC, clement-duport commented
@nathalie-reyre Liste des mail modifié pour la recette : 
"Contact enregistré de création d'un nouveau établissement",
"Lien d'édition du formulaire d'établissement",
"Suggestion de mise à jour d'établissement",
"Mise en relation par mail"

2023-06-15 13:23 UTC, bbohec requested changes

2023-06-15 14:37 UTC, JeromeBu approved these changes

2023-06-16 07:18 UTC, bbohec approved these changes

2023-06-16 07:22 UTC, merged