WIP 211 etq entreprise je réponds directement au candidat qui ma contacté par lintermédiaire dif
gip-inclusion/immersion-facile pull request #380
Opened 2023-06-27 15:46 UTC by enguerranws

2023-07-03 10:46 UTC, JeromeBu commented
La doc se trouve ici : https://www.notion.so/gip-inclusion/Retours-mise-en-place-opacification-des-mails-Brevo-inbound-parsing-f6f9670caca14f04850e6ba1d59e6c06

2023-07-04 10:57 UTC, bbohec requested changes

2023-07-04 10:57 UTC, bbohec commented on back/src/domain/immersionOffer/useCases/ContactEstablishment.ts
> +  }
```suggestion
  private createDiscussion({
    contactRequest,
    contact,
    establishment,
    now,
  }: {
    contactRequest: ContactEstablishmentRequestDto;
    contact: ContactEntity;
    establishment: EstablishmentEntity;
    now: Date;
  }):DiscussionAggregate  {
    return {
      id: this.uuidGenerator.new(),
      appellationCode: contactRequest.appellationCode,
      siret: contactRequest.siret,
      businessName: establishment.customizedName ?? establishment.name,
      createdAt: now,
      immersionObjective:
        contactRequest.contactMode === "EMAIL"
          ? contactRequest.immersionObjective
          : null,
      address: establishment.address,
      potentialBeneficiary: {
        firstName: contactRequest.potentialBeneficiaryFirstName,
        lastName: contactRequest.potentialBeneficiaryLastName,
        email: contactRequest.potentialBeneficiaryEmail,
        phone:
          contactRequest.contactMode === "EMAIL"
            ? contactRequest.potentialBeneficiaryPhone
            : "",
        resumeLink:
          contactRequest.contactMode === "EMAIL"
            ? contactRequest.potentialBeneficiaryResumeLink
            : "",
      },
      establishmentContact: {
        contactMode: contactRequest.contactMode,
        email: contact.email,
        firstName: contact.firstName,
        lastName: contact.lastName,
        phone: contact.phone,
        job: contact.job,
        copyEmails: contact.copyEmails,
      },
      exchanges:
        contactRequest.contactMode === "EMAIL"
          ? [
              {
                subject: "Demande de contact initiée par le bénéficiaire",
                sentAt: now,
                message: contactRequest.message,
                recipient: "establishment",
                sender: "potentialBeneficiary",
              },
            ]
          : [],
    };

  }
```

2023-07-04 10:57 UTC, bbohec commented on back/src/domain/immersionOffer/useCases/ContactEstablishment.ts
> +    });
```suggestion
     await  uow.discussionAggregateRepository.insert(discussion)
     await this.markEstablishmentAsNotSearchableIfLimitReached({
      uow,
      establishmentAggregate,
      contactRequest,
      now,
    });
     await uow.outboxRepository.save(event),


    
```

2023-07-04 10:57 UTC, bbohec commented on back/src/domain/immersionOffer/useCases/ContactEstablishment.unit.test.ts
> +    expect(discussionAggregateRepository.discussionAggregates).toHaveLength(1);
```suggestion

```

2023-07-04 10:57 UTC, bbohec commented on back/src/domain/immersionOffer/useCases/ContactEstablishment.unit.test.ts
> +// });
```suggestion

```

2023-07-04 10:57 UTC, bbohec commented on back/src/domain/immersionOffer/useCases/discussions/AddExchangeToDiscussionAndTransferEmail.ts
> +    private readonly saveNotificationAndRelatedEvent: SaveNotificationAndRelatedEvent, // private readonly timeGateway: TimeGateway,
```suggestion
    private readonly saveNotificationAndRelatedEvent: SaveNotificationAndRelatedEvent
```

2023-07-04 10:57 UTC, bbohec commented on back/src/domain/immersionOffer/useCases/discussions/AddExchangeToDiscussionAndTransferEmail.ts
> +  inputSchema = brevoInboundBodySchema;
```suggestion
  inputSchema = brevoInboundBodySchema;
```
Sous le constructeur

2023-07-04 10:57 UTC, bbohec commented on back/src/domain/immersionOffer/useCases/discussions/AddExchangeToDiscussionAndTransferEmail.ts
> +  private async processBrevoItem(uow: UnitOfWork, item: BrevoEmailItem) {
```suggestion
  }
  
  private async processBrevoItem(uow: UnitOfWork, item: BrevoEmailItem):Promise<void> {
```

2023-07-04 10:57 UTC, bbohec commented on back/src/domain/immersionOffer/useCases/discussions/AddExchangeToDiscussionAndTransferEmail.ts
> +    recipent.Address?.match(/.*_.*@.*immersion-facile.beta.gouv.fr$/),
```suggestion
    recipent.Address?.match(`/.*_.*@${this.replyDomain}$/`),
```

2023-07-04 10:57 UTC, bbohec commented on back/src/domain/immersionOffer/useCases/discussions/AddExchangeToDiscussionAndTransferEmail.unit.test.ts
> +      };
Utiliser le DiscussionAggregateBuilder

2023-07-04 10:57 UTC, bbohec commented on back/src/domain/immersionOffer/useCases/discussions/AddExchangeToDiscussionAndTransferEmail.unit.test.ts
> +      ]);
Fusionner le tout avec un seul expectToEqual

2023-07-04 10:57 UTC, bbohec commented on back/src/domain/immersionOffer/useCases/discussions/AddExchangeToDiscussionAndTransferEmail.unit.test.ts
> +            subject: "My subject",
```suggestion
            subject: "My subject 2",
```

2023-07-04 10:57 UTC, bbohec commented on back/src/domain/immersionOffer/useCases/discussions/AddExchangeToDiscussionAndTransferEmail.unit.test.ts
> +            subject: "My subject",
```suggestion
            subject: "My subject 1",
```

2023-07-04 10:57 UTC, bbohec commented on back/src/domain/immersionOffer/useCases/discussions/AddExchangeToDiscussionAndTransferEmail.unit.test.ts
> +        ...discussion1.exchanges,
```suggestion
        ...discussion2.exchanges,
```

2023-07-04 10:57 UTC, bbohec commented on back/src/domain/immersionOffer/useCases/discussions/AddExchangeToDiscussionAndTransferEmail.unit.test.ts
> +  describe("wrong paths", () => {
```suggestion
  });
  
  describe("wrong paths", () => {
```

2023-07-04 13:57 UTC, bbohec approved these changes

2023-07-04 14:01 UTC, merged