375 mettre un minimum dâge pour la demande de mini stage cci
gip-inclusion/immersion-facile pull request #433
Opened 2023-07-07 13:59 UTC by celineung

2023-07-10 07:54 UTC, bbohec requested changes

2023-07-10 07:54 UTC, bbohec commented on shared/src/convention/ConventionDto.unit.test.ts
> +    });
A voir car c'était pas fait avant mais on pourrait modifier le test pour fournir le message d'erreur attendu `expectConventionDtoToBeInvalid`. Afin d'éviter les faux positifs sur des erreurs qui ne conviendrait pas.

2023-07-10 07:54 UTC, bbohec commented on shared/src/convention/convention.schema.ts
> +      getConventionFieldName("signatories.beneficiary.birthdate"),
```suggestion
      `L'âge du bénéficiaire doit être au minimum de ${miniumAgeRequirement}ans`,
      getConventionFieldName("signatories.beneficiary.birthdate"),
```

2023-07-10 14:35 UTC, celineung commented on shared/src/convention/ConventionDto.unit.test.ts
> +    });
@bbohec c'est pris en compte dans le dernier commit :)

2023-07-12 07:55 UTC, bbohec approved these changes

2023-07-12 08:34 UTC, merged