WIP - added actions to fetch / create establishment form, + tests, plugged in EstablishmentForm
gip-inclusion/immersion-facile pull request #453
Opened 2023-07-12 15:42 UTC by enguerranws

2023-07-18 15:21 UTC, celineung reviewed
suggestion: revoir le wording des commits car ils contiennent encore des "wip"

2023-07-19 08:54 UTC, enguerranws commented
> suggestion: revoir le wording des commits car ils contiennent encore des "wip"

Fait, merci !

2023-07-19 10:16 UTC, bbohec requested changes

2023-07-19 10:16 UTC, bbohec commented on front/src/app/components/forms/establishment/EstablishmentForm.tsx
>            )}
Vérifier dans quel cas on a ce message d'erreur (voir ce qui se passe en cas de fetchError/submitError?)

2023-07-19 10:16 UTC, bbohec commented on front/src/app/components/forms/establishment/EstablishmentForm.tsx
> +      isEstablishmentCreation && mode === "create"
```suggestion
      isEstablishmentCreation && mode === "create"
```

A creuser

2023-07-19 10:16 UTC, bbohec commented on front/src/app/components/forms/establishment/EstablishmentForm.tsx
> +    ...initialFormEstablishment,
Ranger les slips en début de composants (selectors ensembles , tout ce qui est lié à la route ensemble, les useEffects,....)

2023-07-19 10:16 UTC, bbohec commented on front/src/app/components/forms/establishment/CreationSiretRelatedInputs.tsx
> +  const [requestEmailToEditFormError] = useState<string | null>(null);
Tenter de supprimer les deux hooks qui ne n'ont pas de setter.

2023-07-19 10:16 UTC, bbohec commented on front/src/app/components/forms/establishment/CreationSiretRelatedInputs.tsx
> +  const [requestEmailToEditFormError] = useState<string | null>(null);
++ utiliser les feedbacks redux à place de la valeur des hooks supprimés

2023-07-19 13:09 UTC, enguerranws commented on front/src/core-logic/domain/establishmentPath/establishment.slice.ts
> +  jwt: string;
Si je passe en JwtDto, j'ai des erreurs de type au niveau de shared/src/headers.ts. Vu que ça touche toute l'app, ça pourrait être amélioré, mais pas dans cette PR je pense.

2023-07-19 14:34 UTC, JeromeBu approved these changes

2023-07-19 14:34 UTC, bbohec approved these changes

2023-07-19 14:38 UTC, merged