feature/discussion email improvements
gip-inclusion/immersion-facile pull request #457
Opened 2023-07-13 16:32 UTC by enguerranws

- handle attachment in NotificationGateway + responseType in targets
- added notifications_email_attachment on PgNotificationRepository
- added sender email and name to notifications email, no reply email address on email exchanges
- replace immersionFacileContactEmail in exchanges email content
- replace contact mail w/ target blank

2023-07-17 13:40 UTC, JeromeBu reviewed
ca marche ?

2023-07-17 13:40 UTC, JeromeBu commented on back/src/adapters/primary/config/createUseCases.ts
> +          gateways.notification,
truc bidule

2023-07-19 08:07 UTC, bbohec requested changes

2023-07-19 08:08 UTC, bbohec approved these changes

2023-07-19 08:41 UTC, merged