Mettre un champ nom/prénom du prescripteur lors de la validation de convention
gip-inclusion/immersion-facile pull request #572
Opened 2023-08-17 13:26 UTC by celineung

2023-08-18 15:02 UTC, celineung commented on back/package.json
> +    "db:migrations": "ts-node node_modules/node-pg-migrate/bin/node-pg-migrate -j ts -m src/adapters/secondary/pg/migrations",
- mettre aussi les commandes dans le package.json à la racine
- tester `pnpm db:down 2`

2023-08-22 09:35 UTC, JeromeBu commented on back/package.json
> +    "db:migrations": "ts-node node_modules/node-pg-migrate/bin/node-pg-migrate -j ts -m src/adapters/secondary/pg/migrations",
pas trop sur de ton nommage la. Ca pointe bien vers la command `migrate`, le dossier `migrations` n'est qu'un argument.

Pour moi celle-ci serait : `db:migrate` et celle qui s'appelle `db:migrate` en dessous devrait être : `db:up`

2023-08-22 09:35 UTC, JeromeBu commented on back/package.json
> +    "db:migrate": "pnpm db:migrations up",
```suggestion
    "db:up": "pnpm db:migrate up",
```

2023-08-23 14:22 UTC, enguerranws requested changes

2023-08-23 14:22 UTC, enguerranws commented on back/src/utils/concatNames.ts
> +export const concatNames = (validator: ConventionValidator): string =>
```suggestion
export const concatValidatorNames = (validator: ConventionValidator): string =>
```

Et peut être bouger la méthode dans `shared/src/convention/convention.ts` (vu que c'est indissociable de la notion de convention) ?

2023-08-23 14:22 UTC, enguerranws commented on front/src/app/components/admin/conventions/ConventionManageActions.tsx
> +          onClose={() => setValidatorWarningMessage("")}
```suggestion
          onClose={() => setValidatorWarningMessage(null)}
```

Idem

2023-08-23 14:22 UTC, enguerranws commented on front/src/app/components/forms/convention/ConventionFeedbackNotification.tsx
> +  },
```suggestion
    message:
      "La décision de refuser cette immersion est bien enregistrée. Cette décision va être communiquée par mail au bénéficiaire et à l'entreprise.",
  },
```

2023-08-23 14:22 UTC, enguerranws commented on front/src/app/components/forms/convention/ConventionFeedbackNotification.tsx
> +  },
```suggestion
      "Vous allez recevoir un lien de modification par e-mail (peut-être dans une boite générique agence).",
  },
```

2023-08-23 14:22 UTC, enguerranws commented on front/src/app/components/forms/convention/ConventionFeedbackNotification.tsx
> +  },
```suggestion
      "La validation de cette demande est bien enregistrée. La confirmation de cette validation va être communiquée par mail à chacun des signataires.",
  },
```

2023-08-23 14:22 UTC, enguerranws commented on front/src/app/components/forms/convention/ConventionFeedbackNotification.tsx
> +    message: "Succès. La convention a bien été annulée.",
```suggestion
    message: "La convention a bien été annulée.",
```

2023-08-23 14:22 UTC, enguerranws commented on front/src/app/components/forms/convention/ConventionFeedbackNotification.tsx
> +  },
```suggestion
      "La convention a bien été supprimée. La confirmation de cette suppression va être communiquée par mail à chacun des signataires.",
  },
```

2023-08-23 14:22 UTC, enguerranws commented on shared/src/email/emailTemplatesByName.ts
> +        } et la convention est bien enregistrée.
S'il n'y a pas de validatorName, on risque d'avoir une double espace entre `validée` et `et la convention ...`

2023-08-23 14:22 UTC, enguerranws commented on shared/src/email/emailTemplatesByName.ts
> +        } pour que vous l'examiniez.</strong>
Idem ici

2023-08-23 14:22 UTC, enguerranws commented on front/src/app/components/forms/convention/VerificationActionButton.tsx
> +  const onClick = () =>
```suggestion
  const onActionButtonClick = () =>
```

Ou (si onActionButtonClick ne convient pas) quelque chose qui exprime ce sur quoi on click

2023-08-23 14:22 UTC, enguerranws commented on front/src/app/components/forms/convention/VerificationActionButton.tsx
> +        {doesStatusNeedsJustification(newStatus) ? (
Je sais pas si ts-pattern pourrait être intéressant ici, mais je suis pas un gros fan des ternaires dans du JSX (question de goût).

2023-08-28 07:34 UTC, enguerranws approved these changes

2023-08-28 07:39 UTC, merged