Evolution de l'API de recherche : supporter la recherches sur plusieurs Appellations
gip-inclusion/immersion-facile pull request #727
Opened 2023-10-05 12:16 UTC by celineung

2023-10-10 14:46 UTC, enguerranws commented
NB : 
- sur la V1, si on entre pas de param appellation_code, on n'obtient pas de résultats LBB (http://localhost:3000/api/v1/immersion-offers?latitude=48.8535&longitude=2.1&rome=D1214&distance_km=100)
- les requêtes faites par Swagger UI avec un seul code appellation (http://localhost:3000/api/v2/search?appellationCodes=11573&latitude=48.8535&longitude=2.34839&distanceKm=10&voluntaryToImmersion=true&sortedBy=distance) retournent une erreur 400 (lié au format de param array), à fixer dans shared-routes (pas bloquant)
=> les requêtes devraient avoir cette tête : http://localhost:3000/api/v2/search?appellationCodes[]=11573&latitude=48.8535&longitude=2.34839&distanceKm=10&voluntaryToImmersion=true&sortedBy=distance (`appellationCodes[]`)

2023-10-16 09:20 UTC, bbohec requested changes

2023-10-16 10:10 UTC, enguerranws commented on back/src/adapters/primary/routers/search/createSearchRouter.e2e.test.ts
> +          appellationCodes: ["XXX", "12694"],
Je ne crois pas, c'est que ça va prendre un moment à faire côté shared-routes je crois.

2023-10-16 10:41 UTC, JeromeBu commented on back/src/adapters/primary/routers/search/createSearchRouter.e2e.test.ts
> +          appellationCodes: ["XXX", "12694"],
ah si si, ca a été shippé dans la v0.8.16 de shared route, on peut en mettre un seul maintenant

2023-10-16 11:55 UTC, bbohec approved these changes

2023-10-16 11:55 UTC, merged