608 page groupe et page secteur dactitivité + géo pour mise en ligne début nov semaine de lagroalimentaire
gip-inclusion/immersion-facile pull request #729
Opened 2023-10-05 15:20 UTC by JeromeBu

- Change EstablishmentGroup to Group and return group with results
- WIP PG group part with kysely

2023-10-09 12:04 UTC, enguerranws commented on back/src/adapters/secondary/pg/repositories/PgGroupRepository.ts
> +      LEFT JOIN "establishments" e ON e.siret = groups__sirets.siret
Pour info, cette requête est restée en SQL brut, le temps que les tables `establishments`, `immersion_offers`, etc, aient une définition Kysely.

2023-10-09 15:24 UTC, bbohec requested changes

2023-10-09 15:24 UTC, bbohec commented on front/src/app/pages/group/GroupPage.tsx
> +// type GroupTheme = Record<AuthorizedGroupSlugs, Group>;
```suggestion

```

2023-10-09 15:24 UTC, bbohec commented on front/src/app/pages/group/GroupPage.tsx
> +  const getInitialOffers = useCallback(async () => {
```suggestion
  const getInitialGroupData = useCallback(async () => {
```

2023-10-09 15:24 UTC, bbohec commented on front/src/app/pages/group/GroupPage.tsx
> +  if (!group || loading) return <Loader />;
```suggestion

```

2023-10-10 07:23 UTC, enguerranws commented on back/src/adapters/secondary/pg/migrations/1696515768670_add-columns-hero-headers-columns-to-groups-and-rename-establishment-goups-to-groups.ts
> +  });
On garde, comme vu hier.

2023-10-10 07:58 UTC, bbohec approved these changes

2023-10-10 08:05 UTC, merged