fix wrong error on establishment deletion
gip-inclusion/immersion-facile pull request #818
Opened 2023-11-02 13:34 UTC by clement-duport

2023-11-03 11:14 UTC, bbohec approved these changes

2023-11-03 15:38 UTC, JeromeBu requested changes
J'ai l'impression qu'il manque le commit de refacto qu'on a fait ensemble non ?

2023-11-06 08:03 UTC, clement-duport commented
yep je viens de push le commit

2023-11-06 11:29 UTC, JeromeBu approved these changes

2023-11-06 13:41 UTC, merged