Establishment representative inclusion connect dashboard
gip-inclusion/immersion-facile pull request #857
Opened 2023-11-10 16:29 UTC by bbohec

2023-11-13 09:19 UTC, JeromeBu requested changes

2023-11-13 09:19 UTC, JeromeBu commented on shared/src/dashboard/dashboard.dto.ts
> +    "email_repr%C3%A9sentant_de_l'entreprise": Email;
une raison pour le snake_case et le français ici ?

2023-11-13 09:19 UTC, JeromeBu commented on back/src/adapters/secondary/dashboardGateway/MetabaseDashboardGateway.ts
> +      },
ca me gène beaucoup de mettre l'email dans le token (je poursuis la review mais ca vaut coup qu'on en discute)

2023-11-13 11:33 UTC, JeromeBu commented on back/src/adapters/secondary/dashboardGateway/StubDashboardGateway.ts
> +    );
pas trop sur de l'intérêt de ces logs. Je vois que tu as repris comme les autres methodes. à mon avis on peut tous les virer 😅

2023-11-13 11:33 UTC, JeromeBu commented on back/src/domain/inclusionConnectedUsers/useCases/GetInclusionConnectedUser.ts
> +                user.email,
ici je constate que le user vient bien du user inclusion connecté (et pas du token), donc je ne vois pas où c'est utile de l'avoir dans le token

2023-11-13 11:33 UTC, JeromeBu commented on front/src/app/components/layout/LayoutHeader.tsx
> +        // },
On peut le mettre dans le menu déroulant de l'admin pour faciliter la recette et l'usage en test pour l'instant

2023-11-14 08:02 UTC, bbohec commented on shared/src/routes/routes.ts
> +  [allowedStartInclusionConnectLoginPages[1]]: "entreprise-dashboard",
ok quittes à faire du 100% français je suis parti sur 
`  [allowedStartInclusionConnectLoginPages[1]]: "pilotage-etablissement",`

2023-11-14 08:05 UTC, bbohec commented on back/src/adapters/secondary/dashboardGateway/StubDashboardGateway.ts
> +    );
Allez j'en profite pour virer tout les logs sur cet adapter

2023-11-14 11:24 UTC, JeromeBu approved these changes

2023-11-14 16:12 UTC, merged