restrict the kind of agency that can be selected as validation agency for accompanying agency
gip-inclusion/immersion-facile pull request #894
Opened 2023-11-16 12:14 UTC by clement-duport

2023-11-16 13:59 UTC, JeromeBu commented on front/src/app/components/forms/commons/AgencySelector.tsx
> +      .filter((kind): kind is AllowedAgencyKindToAdd => agencyKindFilter(kind))
```suggestion
      .filter(agencyKindFilter)
```

2023-11-16 13:59 UTC, JeromeBu commented on front/src/app/components/forms/commons/AgencySelector.tsx
> +      );
on peut se réunir ça dans un tableau :

```suggestion
     const notFitForDelegationAgencyKind = ["autre", "cci", "operateur-cep", "immersion-facile"]
       [...]
      return (
        !notFitForDelegationAgencyKind.includes(kind)
      );
```

2023-11-16 13:59 UTC, JeromeBu commented on front/src/app/components/forms/commons/AgencySelector.tsx
> +      );
Et pour éviter la double négation ca serait peut-être mieux de faire l'inverse :

```ts
const fitForDelegationAgencyKind: AgencyKind[] = ["pole-emploi", "mission-locale", "etc..."]

return fitForDelegationAgencyKind.includes(kind) 
```

2023-11-17 08:00 UTC, JeromeBu requested changes

2023-11-17 08:00 UTC, JeromeBu commented on front/src/app/components/forms/commons/AgencySelector.tsx
> +  );
on peut gérer le cas `shouldFilterDelegationPrescriptionAgencyKind` directement ici :
```suggestion
  const allInitialKinds = keys(agencyKindToLabel)
  const [agencyKinds, setAgencyKinds] = useState<AllowedAgencyKindToAdd[]>(
    shouldFilterDelegationPrescriptionAgencyKind
      ? fitForDelegationAgencyKind
      : allInitialKinds
  );
```

2023-11-17 12:40 UTC, JeromeBu requested changes

2023-11-17 12:40 UTC, JeromeBu commented on shared/src/agency/agency.dto.ts
> +export const fitForDelegationAgencyKindFiltered = agencyKindList.filter(
on peut renommer : `fitForDelegationAgencyKind`

2023-11-17 12:40 UTC, JeromeBu commented on front/src/app/components/forms/commons/AgencySelector.tsx
> +);
ça ne sert à rien ça car :  `fitForDelegationAgencyKind` = `fitForDelegationAgencyKindFiltered`

2023-11-17 12:40 UTC, JeromeBu commented on front/src/app/components/forms/commons/AgencySelector.tsx
> +  return keys(agencyKindToLabel);
plutôt que de répéter à beaucoup d'endroits `keys(agencyKindToLabel)`, met le resultat dans une variable, genre `const allAgencyKindsAllowedToAdd = keys(agencyKindToLabel)`. Ca sera plus explicit.

2023-11-17 12:40 UTC, JeromeBu commented on front/src/app/components/forms/commons/AgencySelector.tsx
> +  return keys(agencyKindToLabel);
(ca n'a même pas besoin d'être dans le composant)

2023-11-17 16:38 UTC, clement-duport commented on front/src/app/components/forms/commons/AgencySelector.tsx
> +);
Il ne me semble pas que les deux soit égaux vu que fitForDelegationAgencyKindFiltered est construit a partir de agencyKindList qui est un tableau as const.

2023-11-20 08:57 UTC, enguerranws commented on front/src/app/components/forms/commons/AgencySelector.tsx
> +            value: agencyKinds.at(0),
Pas de .at() en front :)

2023-11-20 10:57 UTC, JeromeBu approved these changes

2023-11-20 11:38 UTC, merged