Feature / Convention form multi steps
gip-inclusion/immersion-facile pull request #99
Opened 2023-05-16 15:14 UTC by enguerranws

…ntStep In Redux

2023-05-25 12:40 UTC, enguerranws commented on front/src/app/components/forms/convention/ConventionForm.tsx
> +                validationAction={
validationAction peut être pas très utile, à supprimer.

2023-05-25 12:57 UTC, enguerranws commented on front/src/app/components/forms/convention/ShareConventionLink.tsx
> +        Partager la convention
Rajouter icon ?

2023-05-25 13:21 UTC, enguerranws commented on back/src/adapters/secondary/pg/PgConventionRepository.ts
> -          sanitary_prevention, sanitary_prevention_description, immersion_address, immersion_objective, immersion_appellation, immersion_activities, immersion_skills, postal_code, work_conditions, in
écrire migration pour virer la colonne en base

2023-05-26 08:45 UTC, bbohec requested changes

2023-05-26 08:45 UTC, bbohec commented on front/src/app/components/forms/convention/ConventionSummary.tsx
> +      convention.sanitaryPrevention ? "✅" : "❌",
```suggestion
      fields["individualProtection"].label,
      convention.individualProtection ? "✔️" : "❌",
    ],
    [
      fields["sanitaryPrevention"].label,
      convention.sanitaryPrevention ? "✔️" : "❌",
```

2023-05-26 08:45 UTC, bbohec commented on front/src/app/components/forms/convention/sections/agency/AgencyFormSection.tsx
> +);
Si l'AgencyFormSection contient maintenant que AgencySelector, limite ce composant n'a plus lieu d'être?

2023-05-26 08:45 UTC, bbohec commented on front/src/app/components/forms/convention/sections/hour-location/ImmersionHourLocationSection.tsx
A renommer en ScheduleSection.tsx ?

2023-05-26 08:45 UTC, bbohec commented on front/src/app/contents/forms/convention/textSetup.tsx
> +    title: "4. Lieu et horaires de l'immersion",
```suggestion
    title:
      internshipKind === "immersion"
        ? "4. Lieu et horaires de l'immersion"
        : "4. Lieu et horaires du stage",
```

2023-05-26 08:45 UTC, bbohec commented on front/src/app/pages/convention/ConventionMiniStagePage.tsx
> +};
Attention ici il me semble que la page mini stage doit être présenté dans une iFrame, je ne sais pas si tu l'as prévu

2023-05-26 09:54 UTC, enguerranws commented on front/src/app/components/forms/convention/ConventionSummary.tsx
> +      convention.sanitaryPrevention ? "✅" : "❌",
Le rendu sur macos de ✔️ est pas ouf (une check noire)

2023-05-26 09:57 UTC, enguerranws commented on front/src/app/components/forms/convention/sections/hour-location/ImmersionHourLocationSection.tsx
Il ne contient pas que le Schedule, aussi le immersionAddress

2023-05-26 10:13 UTC, enguerranws commented on front/src/app/pages/convention/ConventionMiniStagePage.tsx
> +};
Là dessus, on a la même chose qu'avant, mais par contre, il faudra checker le rendu si on a un exemple d'utilisation dans un iframe.

2023-05-26 10:14 UTC, enguerranws commented on front/src/app/components/forms/convention/ConventionSignForm.tsx
> +  const alreadySigned = !!currentSignatory?.signedAt;
C'est surtout pour lui donner un sens plus explicite via le nommage : comprendre que `!!currentSignatory?.signedAt` veut dire que le signataire a déjà signé, c'est pas super explicite.

2023-05-30 07:50 UTC, bbohec approved these changes

2023-05-30 07:50 UTC, merged